### ISSUE TITLE
Implement Lerna

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-tools#2]
Will likely want to implement [Lerna](https://lernajs.io) for managing the various monorepos that are Node.JS-based.

**Comment by szul** [comment]
Moving to Azure DevOps/Pipeline might make Lerna unnecessary.

**Comment by cleemullins** [comment]
I don't think moving to Azure Devops will make lerna unnecessary. For that it's worth, we hope to be going down this path fairly soon, and you're more than welcome to learn from our efforts (and us from you!).

**Comment by szul** [comment]
@cleemullins This would be great. Still trying to feel our way around CI/CD for these projects in our spare time ;)

**Comment by cleemullins** [comment]
I hear ya. Doing this "right" has involved quite a bit of learning. Fortunately we're able to look at other open-source projects and largely use the patterns & practices they have established. 

Right now, we're struggling a bit as we have 2 distinct build systems (Travis & Azure Devops). Unifying them, to the extend we can, will make things much easier for us.

**Comment by szul** [comment]
No longer needed for the tools repo.
